// ESLint flat config for the TypeScript workspace packages (CORE-FND-002).
//
// Minimal standard setup: @eslint/js recommended rules plus the
// typescript-eslint recommended rules. Type-aware linting is intentionally
// not enabled yet; every package build already runs 'tsc' in strict mode.
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist/",
      "**/node_modules/",
      "**/bin/",
      "**/obj/",
      // Generated by openapi-typescript (CORE-OAS-002); its formatting is owned by
      // the generator and drift-gated, so it is type-checked by tsc but not linted.
      "packages/contracts/src/openapi.ts",
    ],
  },
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [js.configs.recommended, tseslint.configs.recommended],
  },
);
