namespace LiveCore.Api.Recaps;

/// <summary>
/// Recap aggregate of the Recaps module (CORE-AUD-004, the basic recap model story of the "Audit, Export and
/// Recap" epic).
///
/// A <see cref="Recap"/> is the Core-owned, product-neutral "session summary or structured continuation
/// output" (docs/03_DOMAIN_LANGUAGE.md "Recap"; docs/00_START_HERE.md: a Host can "stream SessionEvents and
/// produce Recaps"; docs/01_PRODUCT_VISION_AND_SCOPE.md: "basic recaps"). It is the durable record of a
/// recap produced for one <see cref="SessionId"/>. It stores no vertical product language — a generic
/// session recap only, never a vertical-specific session-report term
/// (docs/04_PRODUCT_BOUNDARIES.md, csv/forbidden_core_terms.csv); a vertical maps it to its own vocabulary in
/// its UI (docs/03_DOMAIN_LANGUAGE.md vertical mappings) while Core persists only the generic resource.
///
/// GENERIC AND AUTHORIZED — the epic acceptance criterion ("Audit/export/recap are generic and authorized").
/// The recap is authorized along structural axes that are immutable for its lifetime:
/// <list type="bullet">
///   <item>TENANT/WORKSPACE/SESSION SCOPE: the recap is session-scoped, so it carries
///   <see cref="OrganizationId"/> (the tenant; checked before the workspace boundary),
///   <see cref="WorkspaceId"/> and <see cref="SessionId"/>, mirroring <c>SessionEvent</c>
///   (csv/database_tables.csv scopes <c>session_events</c> to <c>session</c>; docs/10_DATABASE_SCHEMA.md:
///   tenant-scoped tables include <c>organization_id</c>, workspace-scoped include <c>workspace_id</c>,
///   session-scoped include <c>session_id</c>). The surrogate <see cref="Id"/> alone never authorizes
///   access: every lookup is scoped by <see cref="OrganizationId"/> and <see cref="WorkspaceId"/> so one
///   workspace's recap can never be reached through another workspace's or another tenant's id (threat T5
///   tenant isolation; threat T1 broken object-level authorization in docs/07_SECURITY_THREAT_MODEL.md).</item>
///   <item>HOST-ONLY BY DEFAULT: the recap <see cref="Summary"/> is host content. The event catalog records
///   that a generated recap is "Participant-visible only after separate reveal"
///   (docs/09_EVENT_CATALOG.md / csv/event_catalog.csv, <c>RecapGenerated</c>), so the audience never
///   receives the body until a later, separate reveal — the <see cref="RecapProjection"/> enforces that
///   host-vs-audience separation (threat T2 visibility leak; the "View host-only content" row of
///   docs/06_AUTHORIZATION_MATRIX.md). That reveal, and any HTTP route, are later stories.</item>
/// </list>
///
/// GENERATED BY. <see cref="GeneratedByUserProfileId"/> records who produced the recap. A recap may be
/// produced by a Host OR by the system (docs/09_EVENT_CATALOG.md: <c>RecapGenerated</c> source "System/Host"),
/// so the column is a NULLABLE foreign key into <c>users</c>: <see cref="GenerateByHost"/> records the
/// authenticated host, <see cref="GenerateBySystem"/> records a system-produced recap with no user. It is
/// also SET NULL when the user is deleted (mirrors <c>ExportJob.RequestedByUserProfileId</c> and
/// <c>Asset.CreatedByUserProfileId</c>): the record of who produced a recap survives the later deletion of
/// that user, so deleting the user anonymizes the producer rather than cascade-deleting the recap. Immutable
/// on the aggregate; a null value means a system recap or an anonymized record.
///
/// IMMUTABLE / WRITE-ONCE. A recap is the produced output of a session, so it is never mutated after
/// creation: every property is get-only and there is no transition method, setter or update path (mirrors the
/// write-once <c>ExportManifest</c> and the append-only <c>AuditLogEntry</c>).
///
/// NO SENSITIVE CONTENT IN LOGS (threat T7). The <see cref="Summary"/> IS the recap's host content, so
/// <see cref="ToString"/> EXCLUDES it and renders identifiers, the version and a coarse length only — a recap
/// can never carry its body into structured logs (docs/07_SECURITY_THREAT_MODEL.md: logs carry identifiers,
/// not content). The body itself is guarded from the audience by the role-based projection, not by logging.
///
/// The actual recap GENERATION command (the producer that writes a recap and emits the
/// <c>RecapGenerated</c> event), the separate participant reveal, and any recap HTTP route with its
/// server-side access authorization are later stories — exactly as CORE-AUD-002 modeled the export job and
/// CORE-AUD-003 the export manifest without their endpoints. This story models the recap, its persistence, its
/// EF migration and its role-based projection.
/// </summary>
public sealed class Recap
{
    /// <summary>
    /// The current recap FORMAT version. A recap is a produced, versioned Core artifact
    /// (docs/02_ARCHITECTURE.md: "every public contract is versioned"); a future change to the recap shape
    /// bumps this so a consumer can tell which layout it is reading (mirrors
    /// <c>ExportManifest.CurrentManifestVersion</c>).
    /// </summary>
    public const int CurrentRecapVersion = 1;

    /// <summary>
    /// Maximum stored length of the generic <see cref="Summary"/> body. Generous enough for a full session
    /// summary or structured continuation output while still rejecting unbounded input; the body is generic
    /// Core content, never a vertical term (AGENTS.md).
    /// </summary>
    public const int MaxSummaryLength = 20_000;

    private Recap(
        Guid id,
        Guid organizationId,
        Guid workspaceId,
        Guid sessionId,
        Guid? generatedByUserProfileId,
        int recapVersion,
        string summary,
        DateTimeOffset generatedAt)
    {
        if (id == Guid.Empty)
        {
            throw new ArgumentException("Recap id must not be empty.", nameof(id));
        }

        if (organizationId == Guid.Empty)
        {
            throw new ArgumentException("Organization id must not be empty.", nameof(organizationId));
        }

        if (workspaceId == Guid.Empty)
        {
            throw new ArgumentException("Workspace id must not be empty.", nameof(workspaceId));
        }

        if (sessionId == Guid.Empty)
        {
            throw new ArgumentException("Session id must not be empty.", nameof(sessionId));
        }

        // The producer link is a recorded user reference; when present it must be a real, non-empty surrogate
        // id. A null value means a system-produced recap or an anonymized record (the column sets null on user
        // deletion), so null is accepted on materialization but an explicit empty id is neither a real user
        // nor a deliberate anonymization and is rejected.
        if (generatedByUserProfileId == Guid.Empty)
        {
            throw new ArgumentException(
                "A generated-by user profile id must not be empty; pass null for a system or anonymized recap.",
                nameof(generatedByUserProfileId));
        }

        if (recapVersion <= 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(recapVersion),
                recapVersion,
                "Recap version must be positive.");
        }

        if (!IsValidSummary(summary))
        {
            throw new ArgumentException("Recap summary violates the summary invariants.", nameof(summary));
        }

        Id = id;
        OrganizationId = organizationId;
        WorkspaceId = workspaceId;
        SessionId = sessionId;
        GeneratedByUserProfileId = generatedByUserProfileId;
        RecapVersion = recapVersion;
        Summary = summary;
        // Normalized to UTC so the persisted timestamptz value is offset-independent
        // (docs/10_DATABASE_SCHEMA.md).
        GeneratedAt = generatedAt.ToUniversalTime();
    }

    /// <summary>Materialization constructor for the persistence layer.</summary>
    private Recap()
    {
        // Non-null reference defaults for the EF materialization path; real values are set from the stored
        // columns. The string default keeps the non-nullable property satisfied before EF assigns it.
        Summary = string.Empty;
    }

    /// <summary>
    /// Surrogate key of the recap row (UUID version 7, time-ordered per docs/10_DATABASE_SCHEMA.md). On its
    /// own it never authorizes access: lookups are always scoped by <see cref="OrganizationId"/> and
    /// <see cref="WorkspaceId"/> (threat T5).
    /// </summary>
    public Guid Id { get; }

    /// <summary>
    /// Tenant boundary of the recap: the id of the organization that owns the workspace this recap belongs to
    /// (the <c>organization_id</c> foreign key into <c>organizations</c>). Immutable; the organization
    /// boundary is checked before the workspace boundary (threat T5; docs/06_AUTHORIZATION_MATRIX.md
    /// authorization principles).
    /// </summary>
    public Guid OrganizationId { get; }

    /// <summary>
    /// Workspace boundary of the recap: the id of the workspace this recap belongs to (the <c>workspace_id</c>
    /// foreign key into <c>workspaces</c>). Immutable; a recap never moves to another workspace (threat T5).
    /// </summary>
    public Guid WorkspaceId { get; }

    /// <summary>
    /// The session this recap summarizes (the <c>session_id</c> foreign key into <c>sessions</c>). Immutable;
    /// a recap belongs to exactly one session for its whole lifetime (threat T5).
    /// </summary>
    public Guid SessionId { get; }

    /// <summary>
    /// The authenticated user that produced the recap (the <c>generated_by</c> foreign key into <c>users</c>),
    /// or <see langword="null"/> for a system-produced recap or an anonymized record. A recap may be produced
    /// by a Host or the system (docs/09_EVENT_CATALOG.md <c>RecapGenerated</c> source "System/Host"). NULLABLE
    /// and SET NULL on user deletion, so the recap survives and is anonymized rather than cascade-deleted
    /// (mirrors <c>ExportJob.RequestedByUserProfileId</c>). Immutable on the aggregate.
    /// </summary>
    public Guid? GeneratedByUserProfileId { get; }

    /// <summary>The recap FORMAT version (see <see cref="CurrentRecapVersion"/>). Immutable.</summary>
    public int RecapVersion { get; }

    /// <summary>
    /// The generic recap body — the session summary or structured continuation output
    /// (docs/03_DOMAIN_LANGUAGE.md "Recap"). This is HOST CONTENT: it is never returned to the audience until
    /// a separate reveal (docs/09_EVENT_CATALOG.md: a generated recap is "Participant-visible only after
    /// separate reveal"), which the <see cref="RecapProjection"/> enforces, and it is EXCLUDED from
    /// <see cref="ToString"/> so it never reaches logs (threat T7). Immutable.
    /// </summary>
    public string Summary { get; }

    /// <summary>When this recap was produced (UTC).</summary>
    public DateTimeOffset GeneratedAt { get; }

    /// <summary>
    /// Produces a recap for the given session, generated by an authenticated Host. The recap records the
    /// tenant, workspace and session it belongs to, the producing host, the current recap format version and
    /// the generic <paramref name="summary"/> body. The caller (a later recap-generation command) supplies the
    /// already-resolved tenant, workspace, session and the authenticated host that produced it.
    /// </summary>
    /// <param name="organizationId">The tenant the recap belongs to (required).</param>
    /// <param name="workspaceId">The workspace the recap belongs to (required).</param>
    /// <param name="sessionId">The session the recap summarizes (required).</param>
    /// <param name="generatedByUserProfileId">The authenticated host that produced the recap (required, non-empty).</param>
    /// <param name="summary">The generic recap body (non-blank, within <see cref="MaxSummaryLength"/>).</param>
    /// <param name="generatedAt">When the recap was produced.</param>
    /// <exception cref="ArgumentException">A required id is empty or the summary violates an invariant.</exception>
    public static Recap GenerateByHost(
        Guid organizationId,
        Guid workspaceId,
        Guid sessionId,
        Guid generatedByUserProfileId,
        string summary,
        DateTimeOffset generatedAt)
    {
        if (generatedByUserProfileId == Guid.Empty)
        {
            throw new ArgumentException(
                "Generated-by user profile id must not be empty.",
                nameof(generatedByUserProfileId));
        }

        return new Recap(
            // UUIDv7 id derived from the produced time so ordering by id (ListBySession) is in
            // produced order even for recaps created in the same wall-clock millisecond.
            Guid.CreateVersion7(generatedAt),
            organizationId,
            workspaceId,
            sessionId,
            generatedByUserProfileId,
            CurrentRecapVersion,
            NormalizeSummary(summary),
            generatedAt);
    }

    /// <summary>
    /// Produces a recap for the given session, generated by the SYSTEM (no user). A recap may be produced
    /// automatically by the platform rather than by a host (docs/09_EVENT_CATALOG.md <c>RecapGenerated</c>
    /// source "System/Host"); the producer is recorded as <see langword="null"/>. Otherwise identical to
    /// <see cref="GenerateByHost"/>.
    /// </summary>
    /// <param name="organizationId">The tenant the recap belongs to (required).</param>
    /// <param name="workspaceId">The workspace the recap belongs to (required).</param>
    /// <param name="sessionId">The session the recap summarizes (required).</param>
    /// <param name="summary">The generic recap body (non-blank, within <see cref="MaxSummaryLength"/>).</param>
    /// <param name="generatedAt">When the recap was produced.</param>
    /// <exception cref="ArgumentException">A required id is empty or the summary violates an invariant.</exception>
    public static Recap GenerateBySystem(
        Guid organizationId,
        Guid workspaceId,
        Guid sessionId,
        string summary,
        DateTimeOffset generatedAt)
        => new(
            // UUIDv7 id derived from the produced time (see GenerateByHost) so ListBySession reads
            // recaps in produced order regardless of same-millisecond construction.
            Guid.CreateVersion7(generatedAt),
            organizationId,
            workspaceId,
            sessionId,
            generatedByUserProfileId: null,
            CurrentRecapVersion,
            NormalizeSummary(summary),
            generatedAt);

    /// <summary>
    /// Whether this recap belongs to exactly the given organization. Empty ids match nothing. This is the
    /// tenant-boundary check, checked before the workspace boundary: a recap belongs only to the organization
    /// it names, never to any other (threat T5).
    /// </summary>
    public bool BelongsToOrganization(Guid organizationId)
        => organizationId != Guid.Empty && OrganizationId == organizationId;

    /// <summary>
    /// Whether this recap belongs to exactly the given workspace. Empty ids match nothing. This is the
    /// workspace-boundary check: a recap belongs only to the workspace it names, never to any other (threat
    /// T5).
    /// </summary>
    public bool BelongsToWorkspace(Guid workspaceId)
        => workspaceId != Guid.Empty && WorkspaceId == workspaceId;

    /// <summary>
    /// Whether this recap summarizes exactly the given session. Empty ids match nothing (threat T5).
    /// </summary>
    public bool BelongsToSession(Guid sessionId)
        => sessionId != Guid.Empty && SessionId == sessionId;

    /// <summary>
    /// Whether this recap is the one identified by the given id WITHIN the given organization and workspace.
    /// All three must match; an empty id matches nothing. The surrogate id is only ever honored inside its
    /// tenant and workspace (threats T1/T5).
    /// </summary>
    public bool Identifies(Guid organizationId, Guid workspaceId, Guid id)
        => BelongsToOrganization(organizationId)
            && BelongsToWorkspace(workspaceId)
            && id != Guid.Empty
            && Id == id;

    /// <summary>
    /// Whether the given value is a valid recap summary: non-blank and within <see cref="MaxSummaryLength"/>.
    /// A recap body is multi-line content (a summary or structured continuation output), so — unlike a
    /// single-line failure reason — newlines are allowed; only an empty/whitespace or oversize body is
    /// rejected.
    /// </summary>
    public static bool IsValidSummary(string? value)
        => !string.IsNullOrWhiteSpace(value) && value.Length <= MaxSummaryLength;

    private static string NormalizeSummary(string summary)
    {
        var trimmed = summary?.Trim() ?? string.Empty;
        if (!IsValidSummary(trimmed))
        {
            throw new ArgumentException("Recap summary violates the summary invariants.", nameof(summary));
        }

        return trimmed;
    }

    /// <summary>
    /// Identifier-only representation that is safe for structured logs: recap id, organization id, workspace
    /// id, session id, the producer (or <c>system</c>), the version and the body LENGTH. The
    /// <see cref="Summary"/> body is deliberately EXCLUDED so no recap content ever reaches logs (threat T7 in
    /// docs/07_SECURITY_THREAT_MODEL.md: logs carry identifiers, not content).
    /// </summary>
    public override string ToString()
        => $"Recap {Id} org={OrganizationId} ws={WorkspaceId} session={SessionId} "
            + $"generatedBy={(GeneratedByUserProfileId is { } producer ? producer.ToString() : "system")} "
            + $"v={RecapVersion} length={Summary.Length}";
}
