#requires -Version 5.1

<#
.SYNOPSIS
    Supply-chain gate logic for the published container images (CORE-DEP-003):
    the CVE-scan pass/fail decision and the SBOM validity check.

.DESCRIPTION
    The CI publish path scans each image it is about to push for known
    vulnerabilities and produces a Software Bill of Materials (SBOM). The scan
    and the SBOM are generated by an external tool (Trivy) in CI, but the
    *decision* that turns a scan report into a published-or-blocked verdict, and
    the check that an SBOM is actually a usable bill of materials, are this
    module's pure functions - so they are deterministically testable from
    seeded fixtures without a registry, a network or a real image
    (scripts/test-image-scan.ps1).

    The gate is fail-closed and configurable: by default a CRITICAL finding
    blocks the publish, and the failing severities can be widened (for example
    to also block HIGH). The SBOM check accepts the two industry-standard
    formats Trivy emits - CycloneDX and SPDX - and requires at least one
    recorded component, so an empty or unrecognized document never counts as a
    produced SBOM.

    Compatible with Windows PowerShell 5.1 and PowerShell 7+ (pwsh) on Linux.
#>

# The vulnerability severities a scan report uses, ordered low to high. The gate
# decision compares a finding's severity against the configured failing set.
$script:KnownSeverity = @('UNKNOWN', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')

function Get-LiveCoreScanJsonValue {
    # Safe property read off a ConvertFrom-Json object: returns the value when the
    # named property exists, otherwise $null. Works the same on Windows PowerShell
    # 5.1 and pwsh, where ConvertFrom-Json yields PSCustomObjects.
    [CmdletBinding()]
    [OutputType([object])]
    param(
        [Parameter(Mandatory = $true)][AllowNull()]$InputObject,
        [Parameter(Mandatory = $true)][string]$Name
    )

    if ($null -eq $InputObject) { return $null }
    $property = $InputObject.PSObject.Properties[$Name]
    if ($null -eq $property) { return $null }
    return $property.Value
}

function ConvertFrom-LiveCoreScanText {
    # Parses JSON text into an object, throwing a clear error on malformed input
    # so the fail-closed callers turn an unparseable report or SBOM into a block.
    [CmdletBinding()]
    [OutputType([object])]
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Text)

    if ([string]::IsNullOrWhiteSpace($Text)) {
        throw 'Empty document: expected JSON content.'
    }
    try {
        return $Text | ConvertFrom-Json
    }
    catch {
        throw "Malformed JSON document: $($_.Exception.Message)"
    }
}

function Get-LiveCoreScanReportModel {
    <#
    .SYNOPSIS
        Parses a Trivy JSON scan report (from a path or literal content) into a
        normalized finding list.
    .OUTPUTS
        A PSCustomObject with ArtifactName (string) and Findings (an array of
        PSCustomObjects carrying Severity, VulnerabilityId, Package, Target and
        FixedVersion).
    #>
    [CmdletBinding()]
    [OutputType([psobject])]
    param(
        [Parameter(Mandatory = $true, ParameterSetName = 'Path')]
        [string]$Path,

        [Parameter(Mandatory = $true, ParameterSetName = 'Content')]
        [AllowEmptyString()]
        [string]$Content
    )

    if ($PSCmdlet.ParameterSetName -eq 'Path') {
        if (-not (Test-Path -LiteralPath $Path)) {
            throw "Scan report not found: $Path"
        }
        $text = [System.IO.File]::ReadAllText($Path)
    }
    else {
        $text = $Content
    }

    $report = ConvertFrom-LiveCoreScanText -Text $text
    $artifactName = [string](Get-LiveCoreScanJsonValue -InputObject $report -Name 'ArtifactName')

    $findings = New-Object System.Collections.Generic.List[psobject]
    foreach ($result in @(Get-LiveCoreScanJsonValue -InputObject $report -Name 'Results')) {
        if ($null -eq $result) { continue }
        $target = [string](Get-LiveCoreScanJsonValue -InputObject $result -Name 'Target')
        foreach ($vulnerability in @(Get-LiveCoreScanJsonValue -InputObject $result -Name 'Vulnerabilities')) {
            if ($null -eq $vulnerability) { continue }
            $severity = [string](Get-LiveCoreScanJsonValue -InputObject $vulnerability -Name 'Severity')
            $findings.Add([pscustomobject]@{
                    Severity        = $severity.ToUpperInvariant()
                    VulnerabilityId = [string](Get-LiveCoreScanJsonValue -InputObject $vulnerability -Name 'VulnerabilityID')
                    Package         = [string](Get-LiveCoreScanJsonValue -InputObject $vulnerability -Name 'PkgName')
                    Target          = $target
                    FixedVersion    = [string](Get-LiveCoreScanJsonValue -InputObject $vulnerability -Name 'FixedVersion')
                })
        }
    }

    return [pscustomobject]@{
        ArtifactName = $artifactName
        Findings     = $findings.ToArray()
    }
}

function Test-LiveCoreScanGate {
    <#
    .SYNOPSIS
        Decides whether a scan report passes the publish gate.
    .DESCRIPTION
        The gate fails when the report carries any finding whose severity is in
        the failing set (CRITICAL by default). Fail-closed: an unknown/blank
        severity never silently passes a finding that would otherwise block.
    .OUTPUTS
        A PSCustomObject with Passed (bool), Blocking (the blocking findings) and
        Counts (a hashtable of severity -> count over all findings).
    #>
    [CmdletBinding()]
    [OutputType([psobject])]
    param(
        [Parameter(Mandatory = $true)][psobject]$Model,
        [string[]]$FailOnSeverity = @('CRITICAL')
    )

    $failSet = @($FailOnSeverity | ForEach-Object { $_.ToUpperInvariant() })

    $counts = [ordered]@{}
    foreach ($severity in $script:KnownSeverity) { $counts[$severity] = 0 }

    $blocking = New-Object System.Collections.Generic.List[psobject]
    foreach ($finding in @($Model.Findings)) {
        if ($null -eq $finding) { continue }
        $severity = $finding.Severity
        if ($counts.Contains($severity)) { $counts[$severity]++ } else { $counts[$severity] = 1 }
        if ($failSet -contains $severity) { $blocking.Add($finding) }
    }

    return [pscustomobject]@{
        Passed   = ($blocking.Count -eq 0)
        Blocking = $blocking.ToArray()
        Counts   = $counts
    }
}

function Get-LiveCoreSbomModel {
    <#
    .SYNOPSIS
        Parses an SBOM (from a path or literal content) into a small model,
        recognizing the CycloneDX and SPDX JSON formats Trivy emits.
    .OUTPUTS
        A PSCustomObject with Format ('CycloneDX', 'SPDX' or 'Unknown'),
        ComponentCount (int) and Identifier (the serial number / SPDX version).
    #>
    [CmdletBinding()]
    [OutputType([psobject])]
    param(
        [Parameter(Mandatory = $true, ParameterSetName = 'Path')]
        [string]$Path,

        [Parameter(Mandatory = $true, ParameterSetName = 'Content')]
        [AllowEmptyString()]
        [string]$Content
    )

    if ($PSCmdlet.ParameterSetName -eq 'Path') {
        if (-not (Test-Path -LiteralPath $Path)) {
            throw "SBOM not found: $Path"
        }
        $text = [System.IO.File]::ReadAllText($Path)
    }
    else {
        $text = $Content
    }

    $document = ConvertFrom-LiveCoreScanText -Text $text

    $bomFormat = [string](Get-LiveCoreScanJsonValue -InputObject $document -Name 'bomFormat')
    $spdxVersion = [string](Get-LiveCoreScanJsonValue -InputObject $document -Name 'spdxVersion')

    if ($bomFormat -eq 'CycloneDX') {
        $components = @(Get-LiveCoreScanJsonValue -InputObject $document -Name 'components')
        return [pscustomobject]@{
            Format         = 'CycloneDX'
            ComponentCount = @($components | Where-Object { $null -ne $_ }).Count
            Identifier     = [string](Get-LiveCoreScanJsonValue -InputObject $document -Name 'serialNumber')
        }
    }

    if (-not [string]::IsNullOrWhiteSpace($spdxVersion)) {
        $packages = @(Get-LiveCoreScanJsonValue -InputObject $document -Name 'packages')
        return [pscustomobject]@{
            Format         = 'SPDX'
            ComponentCount = @($packages | Where-Object { $null -ne $_ }).Count
            Identifier     = $spdxVersion
        }
    }

    return [pscustomobject]@{
        Format         = 'Unknown'
        ComponentCount = 0
        Identifier     = ''
    }
}

function Test-LiveCoreSbom {
    <#
    .SYNOPSIS
        Decides whether a parsed SBOM model is a usable bill of materials.
    .DESCRIPTION
        Valid only when the format is a recognized standard (CycloneDX or SPDX)
        and at least one component/package is recorded, so an empty or
        unrecognized document never counts as a produced SBOM.
    .OUTPUTS
        A PSCustomObject with IsValid (bool) and Findings (string[]).
    #>
    [CmdletBinding()]
    [OutputType([psobject])]
    param([Parameter(Mandatory = $true)][psobject]$Model)

    $findings = New-Object System.Collections.Generic.List[string]

    if ($Model.Format -eq 'Unknown') {
        $findings.Add('SBOM format is not a recognized standard (expected CycloneDX or SPDX).')
    }
    if ($Model.ComponentCount -le 0) {
        $findings.Add('SBOM records no components, so it is not a usable bill of materials.')
    }

    return [pscustomobject]@{
        IsValid  = ($findings.Count -eq 0)
        Findings = $findings.ToArray()
    }
}

Export-ModuleMember -Function `
    Get-LiveCoreScanReportModel, `
    Test-LiveCoreScanGate, `
    Get-LiveCoreSbomModel, `
    Test-LiveCoreSbom
