#requires -Version 5.1

<#
.SYNOPSIS
    Pure analysis behind the contributor IP policy gates (CORE-LIC-004).

.DESCRIPTION
    The Core is AGPL-3.0-or-later and dual-licensed (docs/16_LICENSING.md): a
    commercial license is offered for the uses the AGPL grant does not permit
    (CORE-LIC-002). Two controls keep contribution provenance clean and the
    relicensing option open, and make license context travel with the source:

      1. Developer Certificate of Origin (DCO) sign-off. Every contributed,
         non-merge commit must carry a `Signed-off-by: Name <email>` trailer whose
         email matches the commit author, certifying the contributor has the right
         to submit the work under the project license and grants the dual-license
         right (CONTRIBUTING.md). This module decides, for a commit, whether a
         valid sign-off is present. Merge commits and automated GitHub App bot
         commits (e.g. dependabot[bot], whose noreply author email carries the
         "[bot]" marker and whose sign-off is the App's own support address) are
         exempt, exactly as the common DCO check exempts them: they are not human
         contributions and certify provenance through the App, not a person.

      2. SPDX source headers. Every first-party, hand-authored source file that
         ships in the distribution artifacts - the C# that builds the container
         images and the TypeScript that builds the published packages - must carry
         a `// SPDX-License-Identifier: AGPL-3.0-or-later` header plus a copyright
         line, so a copied file keeps its license context. This module decides the
         in-scope file set, detects the header and produces the canonical header.

    Generated source is excluded: the EF Core migrations
    (apps/api/Persistence/Migrations) are scaffolded by the EF tooling, and
    packages/contracts/src/openapi.ts is generated by openapi-typescript and
    drift-gated (CORE-OAS-002), so a hand-inserted header would be lost on
    regeneration. PowerShell tooling under scripts/ and the .mjs build/test
    helpers are first-party but not shipped in an artifact, so they are out of the
    header scope (the policy is documented in CONTRIBUTING.md).

    This is the pure logic only - no git side effects beyond enumerating tracked
    files, no file writes. The lint scripts (lint-license-headers.ps1,
    lint-dco-signoff.ps1) and the test (test-contributor-policy.ps1) consume it.

    Compatible with Windows PowerShell 5.1 and PowerShell 7+ (pwsh) on Linux.
#>

# The required SPDX license identifier carried by every in-scope source file.
$script:LicenseIdentifier = 'AGPL-3.0-or-later'

# The copyright holder named on the source header. The codebase is first-party
# today, and the DCO keeps contributions inbound under the project license while
# preserving the dual-license right (docs/16_LICENSING.md), so a collective holder
# is the honest, future-proof attribution.
$script:CopyrightHolder = 'The LiveCore Platform contributors'

# Source extensions in scope: the C# that builds the container images and the
# TypeScript that builds the published packages.
$script:HeaderSourceExtensions = @('.cs', '.ts', '.tsx')

# A header line matches the SPDX identifier and a copyright line near the top of
# the file. Both .cs and .ts use `//` line comments, so one comment style covers
# every in-scope file.
$script:SpdxLineRegex = New-Object System.Text.RegularExpressions.Regex(
    '^\s*//\s*SPDX-License-Identifier:\s*AGPL-3\.0-or-later\s*$')
$script:CopyrightLineRegex = New-Object System.Text.RegularExpressions.Regex(
    '^\s*//\s*Copyright\b')

# How many leading lines the header may occupy before code starts. The canonical
# header is two lines; a small window tolerates a blank line or a reordering
# without accepting a header buried far down the file.
$script:HeaderWindow = 5

function Get-LiveCoreLicenseHeaderLine {
    <#
    .SYNOPSIS
        The canonical two SPDX header lines for the given copyright year.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param(
        [Parameter(Mandatory = $true)]
        [int]$Year
    )

    return , @(
        "// SPDX-License-Identifier: $script:LicenseIdentifier",
        "// Copyright (c) $Year $script:CopyrightHolder"
    )
}

function Test-LiveCoreLicenseHeaderPresent {
    <#
    .SYNOPSIS
        True when the content carries the required SPDX header near the top.

    .DESCRIPTION
        Requires both an `SPDX-License-Identifier: AGPL-3.0-or-later` comment line
        and a `// Copyright` comment line within the first few lines. The year and
        exact ordering are not asserted, so the gate does not churn every January.
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$Content
    )

    if ([string]::IsNullOrEmpty($Content)) {
        return $false
    }

    # Split on either line ending; strip a leading UTF-8 BOM if present.
    $normalized = $Content.TrimStart([char]0xFEFF)
    $lines = $normalized -split "`r`n|`n|`r"
    $window = [Math]::Min($script:HeaderWindow, $lines.Count)

    $hasSpdx = $false
    $hasCopyright = $false
    for ($i = 0; $i -lt $window; $i++) {
        if ($script:SpdxLineRegex.IsMatch($lines[$i])) { $hasSpdx = $true }
        if ($script:CopyrightLineRegex.IsMatch($lines[$i])) { $hasCopyright = $true }
    }

    return ($hasSpdx -and $hasCopyright)
}

function Get-LiveCoreContentWithLicenseHeader {
    <#
    .SYNOPSIS
        The content with the canonical SPDX header prepended.

    .DESCRIPTION
        Pure transform: prepends the two header lines and a blank separator,
        preserving the content's existing line ending and body verbatim. The line
        ending is auto-detected from the content (CRLF if any is present, else LF)
        so a Windows or Linux working copy keeps its EOL and dotnet format /
        Prettier see no incidental change.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$Content,

        [Parameter(Mandatory = $true)]
        [int]$Year
    )

    $eol = if ($Content -match "`r`n") { "`r`n" } else { "`n" }
    $header = (Get-LiveCoreLicenseHeaderLine -Year $Year) -join $eol
    return $header + $eol + $eol + $Content
}

function Test-LiveCoreSourceFileInScope {
    <#
    .SYNOPSIS
        True when a repo-relative path is an in-scope, header-bearing source file.

    .DESCRIPTION
        Pure string predicate (no disk access) so the scope rule is testable on
        its own. In scope: tracked .cs/.ts/.tsx. Out of scope: build output,
        the EF Core migrations (scaffolded), the generated OpenAPI contract types
        and TypeScript declaration files.
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$Path
    )

    if ([string]::IsNullOrWhiteSpace($Path)) { return $false }
    # git ls-files yields forward-slash, repo-relative paths.
    $normalized = $Path.Trim() -replace '\\', '/'

    # Build/vendor output (defensive: git ls-files does not return gitignored output).
    if ($normalized -match '(^|/)(bin|obj|node_modules|dist|coverage|TestResults|\.git)(/|$)') {
        return $false
    }
    # EF Core migrations are scaffolded by the tooling, not hand-authored source.
    if ($normalized -match '(^|/)Persistence/Migrations/') { return $false }
    # Generated OpenAPI-derived contract types (CORE-OAS-002), drift-gated.
    if ($normalized -ieq 'packages/contracts/src/openapi.ts') { return $false }
    # TypeScript declaration files are generated build output.
    if ($normalized.ToLowerInvariant().EndsWith('.d.ts')) { return $false }

    $extension = [System.IO.Path]::GetExtension($normalized).ToLowerInvariant()
    return ($script:HeaderSourceExtensions -contains $extension)
}

function Get-LiveCoreHeaderSourceFile {
    <#
    .SYNOPSIS
        The in-scope source files under the repository, via `git ls-files`.

    .DESCRIPTION
        Enumerates TRACKED files only, so gitignored local tooling and build
        output are never returned. Fails closed (throws) when git cannot enumerate
        the tracked set, like the boundary scan.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoRoot
    )

    $tracked = @(& git -C $RepoRoot ls-files)
    if ($LASTEXITCODE -ne 0) {
        throw "git ls-files exited with code $LASTEXITCODE in $RepoRoot; a git work tree is required."
    }

    $inScope = @(
        $tracked |
            Where-Object { $_ -and $_.Trim() -ne '' } |
            ForEach-Object { $_.Trim() } |
            Where-Object { Test-LiveCoreSourceFileInScope -Path $_ } |
            Sort-Object
    )
    return , $inScope
}

function Get-LiveCoreLicenseHeaderReport {
    <#
    .SYNOPSIS
        Reconciles the in-scope source files against the SPDX header requirement.

    .DESCRIPTION
        Returns the checked file count, the repo-relative paths missing the header,
        and an IsClean verdict (no in-scope file is missing the header).
    #>
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter(Mandatory = $true)]
        [string]$RepoRoot
    )

    $RepoRoot = (Resolve-Path -Path $RepoRoot).Path
    $files = Get-LiveCoreHeaderSourceFile -RepoRoot $RepoRoot

    $missing = New-Object System.Collections.Generic.List[string]
    foreach ($relativePath in $files) {
        $fullPath = Join-Path $RepoRoot $relativePath
        if (-not (Test-Path -LiteralPath $fullPath)) { continue }
        $content = [System.IO.File]::ReadAllText($fullPath)
        if (-not (Test-LiveCoreLicenseHeaderPresent -Content $content)) {
            $missing.Add($relativePath)
        }
    }

    return [pscustomobject]@{
        Checked = $files.Count
        Missing = $missing.ToArray()
        IsClean = ($missing.Count -eq 0)
    }
}

function Get-LiveCoreSignOffEmail {
    <#
    .SYNOPSIS
        The lower-cased emails of every `Signed-off-by:` trailer in a message.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$Message
    )

    $emails = New-Object System.Collections.Generic.List[string]
    if ([string]::IsNullOrEmpty($Message)) {
        return , $emails.ToArray()
    }

    # DCO trailer: "Signed-off-by: Display Name <email@example.com>" (the trailer
    # keyword is case-insensitive; the email is captured from the angle brackets).
    $regex = New-Object System.Text.RegularExpressions.Regex(
        '(?im)^\s*Signed-off-by:\s*.+?<([^>]+)>\s*$')
    foreach ($match in $regex.Matches($Message)) {
        $emails.Add($match.Groups[1].Value.Trim().ToLowerInvariant())
    }
    return , $emails.ToArray()
}

function Test-LiveCoreCommitSignOff {
    <#
    .SYNOPSIS
        True when the message carries a sign-off whose email matches the author.

    .DESCRIPTION
        The DCO requires the sign-off to identify the contributor. The gate is
        satisfied when at least one `Signed-off-by:` trailer's email equals the
        commit author's email (case-insensitive), the rule the common DCO check
        applies.
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$AuthorEmail,

        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$Message
    )

    if ([string]::IsNullOrWhiteSpace($AuthorEmail)) { return $false }
    $author = $AuthorEmail.Trim().ToLowerInvariant()
    $signOffs = Get-LiveCoreSignOffEmail -Message $Message
    return ($signOffs -contains $author)
}

function Test-LiveCoreBotAuthor {
    <#
    .SYNOPSIS
        True when an author email is an automated GitHub App / bot identity.

    .DESCRIPTION
        GitHub App bot accounts (e.g. dependabot[bot]) commit under a noreply email
        of the form "<id>+<name>[bot]@users.noreply.github.com" - the "[bot]@"
        marker is unique to App identities. Such commits are automated dependency or
        maintenance updates, not human contributions, and carry the App's own
        sign-off (e.g. "Signed-off-by: dependabot[bot] <support@github.com>") whose
        email need not equal the author. They are exempt from the DCO author-email
        match, exactly as merge commits are. A plain "noreply@github.com" web-flow
        author (a human committing through the GitHub UI) is NOT a bot.
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyString()]
        [string]$AuthorEmail
    )

    if ([string]::IsNullOrWhiteSpace($AuthorEmail)) { return $false }
    return ($AuthorEmail -match '(?i)\[bot\]@')
}

function Get-LiveCoreSignOffReport {
    <#
    .SYNOPSIS
        Reconciles a set of commits against the DCO sign-off requirement.

    .DESCRIPTION
        $Commits is an array of objects with Sha, AuthorEmail, Message and IsMerge.
        Merge commits and automated GitHub App bot commits (Test-LiveCoreBotAuthor)
        are skipped - they introduce no human-contributed change and the common DCO
        check exempts them. Returns the checked count, the unsigned commits and an
        IsClean verdict.
    #>
    [CmdletBinding()]
    [OutputType([pscustomobject])]
    param(
        [Parameter(Mandatory = $true)]
        [AllowEmptyCollection()]
        [object[]]$Commits
    )

    $checked = 0
    $unsigned = New-Object System.Collections.Generic.List[object]
    foreach ($commit in $Commits) {
        if ($commit.IsMerge) { continue }
        if (Test-LiveCoreBotAuthor -AuthorEmail $commit.AuthorEmail) { continue }
        $checked++
        if (-not (Test-LiveCoreCommitSignOff -AuthorEmail $commit.AuthorEmail -Message $commit.Message)) {
            $unsigned.Add($commit)
        }
    }

    return [pscustomobject]@{
        Checked  = $checked
        Unsigned = $unsigned.ToArray()
        IsClean  = ($unsigned.Count -eq 0)
    }
}

Export-ModuleMember -Function `
    Get-LiveCoreLicenseHeaderLine, `
    Test-LiveCoreLicenseHeaderPresent, `
    Get-LiveCoreContentWithLicenseHeader, `
    Test-LiveCoreSourceFileInScope, `
    Get-LiveCoreHeaderSourceFile, `
    Get-LiveCoreLicenseHeaderReport, `
    Get-LiveCoreSignOffEmail, `
    Test-LiveCoreCommitSignOff, `
    Test-LiveCoreBotAuthor, `
    Get-LiveCoreSignOffReport
